module.exports = Object.freeze({
    MAIN_INSTAGRAM_REWARD: 'pugachevmark',
    REWARD_FOR_INIT: 1,
    REWARD_FOR_INSTAGRAM: 3,
    REWARD_FOR_INVITATION_INIT: 2,
    REWARD_FOR_INIVITATION_INSTAGRAM: 4,
    REWARD_FOR_INVITATION_AMOUNT: 0.1
});